CREATE TABLE it_grundschutz_module ( code VARCHAR(20) NOT NULL PRIMARY KEY,
                                     name VARCHAR(160) NOT NULL,
                                     _order  SERIAL

);

CREATE TABLE it_grundschutz_elementary_threat ( code VARCHAR(20) NOT NULL PRIMARY KEY,
                                                name VARCHAR(160) NOT NULL,
                                                _order SERIAL
);

INSERT INTO it_grundschutz_module VALUES ('ISMS_1','ISMS.1 Security Management'),
                                         ('ORP_1','ORP.1 Organisation'),
                                         ('ORP_2','ORP.2 Personnel'),
                                         ('ORP_3','ORP.3 Awareness and Training in Information Security'),
                                         ('ORP_4','ORP.4 Identity and Access Management'),
                                         ('ORP_5','ORP.5 Compliance Management'),
                                         ('CON_1','CON.1 Crypto Concept'),
                                         ('CON_2','CON.2 Data Protection'),
                                         ('CON_3','CON.3 Backup Concept'),
                                         ('CON_6','CON.6 Deleting and Destroying Data and Devices'),
                                         ('CON_7','CON.7 Information Security on Trips Abroad'),
                                         ('CON_8','CON.8 Software Development'),
                                         ('CON_9','CON.9 Information Exchange'),
                                         ('CON_10','CON.10 Development of Web Applications'),
                                         ('OPS_1_1_2','OPS.1.1.2 Proper IT Administration'),
                                         ('OPS_1_1_3','OPS.1.1.3 Patch and Change Management'),
                                         ('OPS_1_1_4','OPS.1.1.4 Protection Against Malware'),
                                         ('OPS_1_1_5','OPS.1.1.5 Logging'),
                                         ('OPS_1_1_6','OPS.1.1.6 Software Tests and Approvals'),
                                         ('OPS_1_1_7','OPS.1.1.7 System Management'),
                                         ('OPS_1_2_2','OPS.1.2.2 Archiving'),
                                         ('OPS_1_2_4','OPS.1.2.4 Teleworking'),
                                         ('OPS_1_2_5','OPS.1.2.5 Remote Maintenance'),
                                         ('OPS_1_2_6','OPS.1.2.6 NTP Time Synchronisation'),
                                         ('OPS_2_1','OPS.2.1 Outsourcing for Customers'),
                                         ('OPS_2_2','OPS.2.2 Cloud Usage'),
                                         ('OPS_3_1','OPS.3.1 Outsourcing for Service Providers'),
                                         ('DER_1','DER.1 Detecting Security-Relevant Events'),
                                         ('DER_2_1','DER.2.1 Security Incident Handling'),
                                         ('DER_2_2','DER.2.2 Provisions for IT Forensics'),
                                         ('DER_2_3','DER.2.3 Clean-Up of Extensive Security Incidents'),
                                         ('DER_3_1','DER.3.1 Audits and Revisions'),
                                         ('DER_3_2','DER.3.2 Audits Based on the BSI “Guideline for IS Audits”'),
                                         ('DER_4','DER.4 Business Continuity Management'),
                                         ('APP_1_1','APP.1.1 Office Products'),
                                         ('APP_1_2','APP.1.2 Web Browsers'),
                                         ('APP_1_4','APP.1.4 Mobile Applications (Apps)'),
                                         ('APP_2_1','APP.2.1 General Directory Service'),
                                         ('APP_2_2','APP.2.2 Active Directory'),
                                         ('APP_2_3','APP.2.3 OpenLDAP'),
                                         ('APP_3_1','APP.3.1 Web Applications and Web Services'),
                                         ('APP_3_2','APP.3.2 Web Servers'),
                                         ('APP_3_3','APP.3.3 File Servers'),
                                         ('APP_3_4','APP.3.4 Samba'),
                                         ('APP_3_6','APP.3.6 DNS Servers'),
                                         ('APP_4_2','APP.4.2 SAP ERP Systems'),
                                         ('APP_4_3','APP.4.3 Relational Database Systems'),
                                         ('APP_4_4','APP.4.4 Kubernetes'),
                                         ('APP_4_6','APP.4.6 SAP ABAP Programming'),
                                         ('APP_5_2','APP.5.2 Microsoft Exchange and Outlook'),
                                         ('APP_5_3','APP.5.3 General E-Mail Clients and Servers'),
                                         ('APP_6','APP.6 General Software'),
                                         ('APP_7','APP.7 Development of Individual Software'),
                                         ('SYS_1_1','SYS.1.1 General Server'),
                                         ('SYS_1_2_2','SYS.1.2.2 Windows Server 2012'),
                                         ('SYS_1_3','SYS.1.3 Linux and Unix Servers'),
                                         ('SYS_1_5','SYS.1.5 Virtualisation'),
                                         ('SYS_1_6','SYS.1.6 Containerisation'),
                                         ('SYS_1_7','SYS.1.7 IBM Z'),
                                         ('SYS_1_8','SYS.1.8 Storage Solutions'),
                                         ('SYS_2_1','SYS.2.1 General Client'),
                                         ('SYS_2_2_2','SYS.2.2.2 Windows 8.1 Clients'),
                                         ('SYS_2_2_3','SYS.2.2.3 Windows 10 Clients'),
                                         ('SYS_2_3','SYS.2.3 Linux and Unix Clients'),
                                         ('SYS_2_4','SYS.2.4 macOS Clients'),
                                         ('SYS_3_1','SYS.3.1 Laptops'),
                                         ('SYS_3_2_1','SYS.3.2.1 General Smartphones and Tablets'),
                                         ('SYS_3_2_2','SYS.3.2.2 Mobile Device Management (MDM)'),
                                         ('SYS_3_2_3','SYS.3.2.3 iOS (for Enterprise)'),
                                         ('SYS_3_2_4','SYS.3.2.4 Android'),
                                         ('SYS_3_3','SYS.3.3 Mobile Telephones'),
                                         ('SYS_4_1','SYS.4.1 Printers, Copiers, and All-in-One Devices'),
                                         ('SYS_4_3','SYS.4.3 Embedded Systems'),
                                         ('SYS_4_4','SYS.4.4 General IoT Devices'),
                                         ('SYS_4_5','SYS.4.5 Removable Media'),
                                         ('IND_1','IND.1 Process Control and Automation Technology'),
                                         ('IND_2_1','IND.2.1 General ICS Components'),
                                         ('IND_2_2','IND.2.2 Programmable Logic Controller (PLC)'),
                                         ('IND_2_3','IND.2.3 Sensors and Actuators'),
                                         ('IND_2_4','IND.2.4 Machine'),
                                         ('IND_2_7','IND.2.7 Safety Instrumented Systems'),
                                         ('IND_3_2','IND.3.2 Remote Maintenance in Industry'),
                                         ('NET_1_1','NET.1.1 Network Architecture and Design'),
                                         ('NET_1_2','NET.1.2 Network Management'),
                                         ('NET_2_1','NET.2.1 WLAN Operation'),
                                         ('NET_2_2','NET.2.2 WLAN Usage'),
                                         ('NET_3_1','NET.3.1 Routers and Switches'),
                                         ('NET_3_2','NET.3.2 Firewall'),
                                         ('NET_3_3','NET.3.3 VPN'),
                                         ('NET_4_1','NET.4.1 Telecommunications Systems'),
                                         ('NET_4_2','NET.4.2 VoIP'),
                                         ('NET_4_3','NET.4.3 Fax Machines and Fax Servers'),
                                         ('INF_1','INF.1 Generic Building'),
                                         ('INF_2_','INF.2 Data Centre and Server Room'),
                                         ('INF_5','INF.5 Room or Cabinet for Technical Infrastructure'),
                                         ('INF_6','INF.6 Storage Media Archives'),
                                         ('INF_7','INF.7 Office Workplace'),
                                         ('INF_8','INF.8 Working from Home'),
                                         ('INF_9','INF.9 Mobile Workplace'),
                                         ('INF_10','INF.10 Meeting, Event, and Training Rooms'),
                                         ('INF_11','INF.11 General Vehicle'),
                                         ('INF_12','INF.12 Cabling'),
                                         ('INF_13','INF.13 Technical Building Management (TBM)'),
                                         ('INF_14','INF.14 Building Automation and Control Systems (BACS)')
;

INSERT INTO it_grundschutz_elementary_threat VALUES ('G_0_1', 'G 0.1 Fire'),
                                                    ('G_0_2', 'G 0.2 Unfavourable Climatic Conditions'),
                                                    ('G_0_3', 'G 0.3 Water'),
                                                    ('G_0_4', 'G 0.4 Pollution, Dust, Corrosion'),
                                                    ('G_0_5', 'G 0.5 Natural Disasters'),
                                                    ('G_0_6', 'G 0.6 Catastrophes in the Vicinity'),
                                                    ('G_0_7', 'G 0.7 Major Events in the Vicinity'),
                                                    ('G_0_8', 'G 0.8 Failure or Disruption of the Power Supply'),
                                                    ('G_0_9', 'G 0.9 Failure or Disruption of Communication Networks'),
                                                    ('G_0_10', 'G 0.10 Failure or Disruption of Supply Networks'),
                                                    ('G_0_11', 'G 0.11 Failure or Disruption of Service Providers'),
                                                    ('G_0_12', 'G 0.12 Electromagnetic Interference'),
                                                    ('G_0_13', 'G 0.13 Interception of Compromising Interference Signals'),
                                                    ('G_0_14', 'G 0.14 Interception of Information / Espionage'),
                                                    ('G_0_15', 'G 0.15 Eavesdropping'),
                                                    ('G_0_16', 'G 0.16 Theft of Devices, Storage Media and Documents'),
                                                    ('G_0_17', 'G 0.17 Loss of Devices, Storage Media and Documents'),
                                                    ('G_0_18', 'G 0.18 Poor Planning or Lack of Adaptation'),
                                                    ('G_0_19', 'G 0.19 Disclosure of Sensitive Information'),
                                                    ('G_0_20', 'G 0.20 Information or Products from an Unreliable Source'),
                                                    ('G_0_21', 'G 0.21 Manipulation with Hardware or Software'),
                                                    ('G_0_22', 'G 0.22 Manipulation of Information'),
                                                    ('G_0_23', 'G 0.23 Unauthorised Access to IT Systems'),
                                                    ('G_0_24', 'G 0.24 Destruction of Devices or Storage Media'),
                                                    ('G_0_25', 'G 0.25 Failure of Devices or Systems'),
                                                    ('G_0_26', 'G 0.26 Malfunction of Devices or Systems'),
                                                    ('G_0_27', 'G 0.27 Lack of Resources'),
                                                    ('G_0_28', 'G 0.28 Software Vulnerabilities or Errors'),
                                                    ('G_0_29', 'G 0.29 Violations of Laws or Regulations'),
                                                    ('G_0_30', 'G 0.30 Unauthorised Use or Administration of Devices and Systems'),
                                                    ('G_0_31', 'G 0.31 Incorrect Use or Administration of Devices and Systems'),
                                                    ('G_0_32', 'G 0.32 Misuse of Authorisation'),
                                                    ('G_0_33', 'G 0.33 Shortage of Personnel'),
                                                    ('G_0_34', 'G 0.34 Assault'),
                                                    ('G_0_35', 'G 0.35 Coercion, Blackmail or Corruption'),
                                                    ('G_0_36', 'G 0.36 Identity theft'),
                                                    ('G_0_37', 'G 0.37 Repudiation of Actions'),
                                                    ('G_0_38', 'G 0.38 Misuse of Personal Information'),
                                                    ('G_0_39', 'G 0.39 Malware'),
                                                    ('G_0_40', 'G 0.40 Denial of Service'),
                                                    ('G_0_41', 'G 0.41 Sabotage'),
                                                    ('G_0_42', 'G 0.42 Social Engineering'),
                                                    ('G_0_43', 'G 0.43 Attack with Specially Crafted Messages'),
                                                    ('G_0_44', 'G 0.44 Unauthorised Entry to Premises'),
                                                    ('G_0_45', 'G 0.45 Data Loss'),
                                                    ('G_0_46', 'G 0.46 Loss of Integrity of Sensitive Information'),
                                                    ('G_0_47', 'G 0.47 Harmful Side Effects of IT-Supported Attacks')
;